### PR TITLE
Basic Linux support

### PR DESCRIPTION
**Pull request by DarkLotus**
Not sure if your wanting PR's like this, but i had always wanted to play around with a PS emulator in C#, and since im on linux got it building there.
I've wrapped these fixes in a platform check as it disabling doublebuffering is a bit of a hack to stop crashes.

* Few minor fixes to get it running on Mono on linux.
* Removal of double buffering results in tearing but solves crashing every few minutes.
* Also added .iso to the file picker.

Below is the exception when using double buffering.
`System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]
  at System.Drawing.GDIPlus.CheckStatus (System.Drawing.Status status) [0x00098] in <954bb0211179498a9465d5f89b2a3d40>:0 
  at System.Drawing.Region.Exclude (System.Drawing.Rectangle rect) [0x0000e] in <954bb0211179498a9465d5f89b2a3d40>:0 
  at (wrapper remoting-invoke-with-check) System.Drawing.Region.Exclude(System.Drawing.Rectangle)
  at System.Windows.Forms.Control+DoubleBuffer.End (System.Windows.Forms.PaintEventArgs pe) [0x00056] in <7346aaf818a24e898fc55461ebf690ad>:0 
  at System.Windows.Forms.Control.WmPaint (System.Windows.Forms.Message& m) [0x00086] in <7346aaf818a24e898fc55461ebf690ad>:0 
`

### CODE REVIEW

**Comment by BluestormDNA** [comment]
Hello there!

I need to finish some things on the GPU to support fillRules and get rid of those clear diagonals on rects first but i plan on actually removing the NetCore3 branch (where i have been doing some SIMD Intrinsics and Span<T> tests locally) and create and stall a Net48 Branch and move main branch of the project to NetCore3.1

Have you checked on linux if those workarounds are needed on the current NetCore 3 branch?

About the ISO files: to tell the true I havent checked onto the format as currently there is only support for Track1 of bin/cue so not quite sure how the file/Cdda layout is inside that format.
Anyway the bin/cue seems the go to format and before supporting more of them (if that ever happens) a proper cue parser would be needed to handle cdda tracks.
Recently some work related to that have been made on:
https://github.com/BluestormDNA/ProjectPSX/commit/c841d2a1e37bd6f2c7504132f6159d1d7b7feb4b and https://github.com/BluestormDNA/ProjectPSX/commit/588890615d5d044c8d890a22e2657dc4012396ff I think those made among others Wipeout3 playable

Im interested on going multiplatform and WinForms actually is a drag arround that that needs to be addressed. Somehow i allways return to dma/cdrom things, but recently ive been looking at https://github.com/AvaloniaUI/Avalonia and https://github.com/Ultz/Silk.NET maybe i shouldn't have scrapped the SDL2 branch...

Anyway.... what game did you try?

**Comment by DarkLotus** [comment]
Tested with FF5/6/7 now, FF5/6 work atleast to the mainmenu not gone further, FF7 in game and appears to all work fine like on windows.

Netcore branch isnt possible to test on linux as far as i know there is no port of mono's winforms to netcore.

There isnt really much to support with an ISO, its just a sector by sector copy of a disc, seemed to work out of the box from testing.

SDL2 is probably the best choice but as you've mentioned the winforms portion is a very small shim so different frontend's can be attached later, winforms does the job for now.

**Comment by BluestormDNA** [comment]
From PSX-SPX:

> .ISO - A raw ISO9660 image (can contain a single data track only)
> Contains raw sectors without any sub-channel information (and thus it's restricted to the ISO filesystem region only, and cannot contain extras like additional audio tracks or additional sessions). The image should start at 00:02:00 (although I wouldn't be surprised if some <might> start at 00:00:00 or so). Obviously, all sectors must have the same size, either 800h or 930h bytes (if the image contains only Mode1 or Mode2/Form1 sectors then 800h bytes would usually enough; if it contains one or more Mode2/Form2 sectors then all sectors should be 930h bytes).
> Handling .ISO files does thus require to detect the image's sector size, and to search the sector that contains the first ISO Volume Descriptor. In case of 800h byte sectors it may be additionally required to detect if it is a Mode1 or Mode2/Form1 image; for PSX images (and any CD-XA images) it'd be Mode2.

I think that if it works right now it probably dosn't for every game and anyway as i understand it will break when further progress is made and we will need to check for sector headers and sub channel data for XA handling. Something that next to the CUE parser (Gran Turismo would need this) is next on the CDROM btw.

Surprissing list of games... recently got FF8 booting and my next goal is to fix DMA blocks to boot FF9 ;)

**Comment by BluestormDNA** [comment]
Hey, hello there... been busy and recently came back to this PR... can you change the base branch to the net framework branch so i can merge this? Thx!

**Pull request closed without merging**
