### PR TITLE
Launch window

### PR DESCRIPTION
**Pull request by Gaweph**
## Added Launch Window

- User can pick location of Bios file
- User can pick location of game file
- These settings are preserved in user settings across application sessions

image

### CODE REVIEW

**Review by BluestormDNA — APPROVED** [review]

**Comment by BluestormDNA** [comment]
I'm ok with the first two commits but for the other 2 there's no need to work on winforms it's gonna be scrapped soon. Any work should go to AvaloniaUI. Or other multiplatform UI when going .NET Core 3 on the nexts weeks

**Comment by Gaweph** [comment]
Can you clarify which commits you are ok with? (the resx removal for example only exists because the Launch form was added and I forgot to remove the resx before the initial commit to the branch)

Do you want me to change anything, or close the PR.  Or are you happy to include for now until somethnig other than WinForms is used to select the game files.

**Review by BluestormDNA — CHANGES_REQUESTED** [review]
Only https://github.com/BluestormDNA/ProjectPSX/pull/4/commits/04886bec95d7bbb83ca906b3e065c3ca0d5749d2 should be merged as there's no need for winform development as it will go away when .NET Core 3.0 comes and hopefully a switch to a multiplatform UI happens...

Btw remember to run the project as Release. It really makes it perform a lot better.

**Comment by Gaweph** [comment]
I have createrd a new PR for this #5 .  Seemed neater.  I will close this PR.

**Pull request closed without merging**
