### PR TITLE
Fix Backward Branches

### PR DESCRIPTION
**Pull request by fraser125**
Thanks for a great start to my project! 
I found this bug, and thought I'd share the fix back to your project. 
Instruction: 1000fffc
was being decoded as b +262,128
Should decode to: b -16

### CODE REVIEW

**Comment by BluestormDNA** [comment]
Thanks, this went unnoticed as imm_s is casted back to uint... i should really refactor the opcode struct.
Have you found any software or test that relies on this behaviour?

**Comment by BluestormDNA** [comment]
Arrived at home today after holidays.
Upon further inspection the original code seems to work as expected even with the 0x1000fffc instruction.

It is true that imm_s might appear to have a wrong value as it's not casted to short but to short and then to uint but it's actually valid.
262128 << 2  = 4294967280 wich is -16
it just overflows when adding to the PC (as it is an uint) thus effectively handling a substraction on an unsigned context.

I will leave this open for some time in case you have something to add.

Glad that ProjectPSX helped you in your own project.

**Comment by fraser125** [comment]
It looks like you are correct, I'm sorry for the confusion. 
I'm not sure what my problem was, but I'm past it now. 
Thank you for taking the time to verify, I checked your results as well and checked that the original version does compile to fewer instructions so I'll revert my code as well. 

If I find anything else I'll let you know. After triple checking my results ;)

**Comment by fraser125** [comment]
I'm still happy to be proven wrong but I brought a lot more data this time. ;)
So I experienced the same weird case where the emulated CPU just ran straight off into the weeds. 
image
The encoded version of the instruction at 0xBFC13644 is 
`268500988	0x1000FFFC`
I added the following code to prove or disprove if it was related to the code we've been discussing
image
By the fact that I hit the breakpoint, it appears to be related. 

For reference here is the code block from Ghidra
image

Looking back at the second screenshot with C# code, both calculated values are visible and are clearly different. 
```
PC_Predictor = PC + (instr.imm_s << 2);
	3217372728		0xBFC5 3638
var s = (uint)(PC + (short)(instr.imm_s << 2));
	3217110584		0xBFC1 3638
```
It appears that the 18th bit is different between the 2 calculations, I believe only up to the 17th bit should ever be modified by a branch instruction (15..0 << 2).  There is a 5 in the original code and a 1 in the casting version of the code. 
The Ghidra screenshot shows that the branch is only going up a few instructions. (The label names, etc are mine). 
I'm happy to perform additional tests and please do challenge me. My code is clearly modified from your original, but I believe the single line of code is the problem. 
Thanks!

**Comment by BluestormDNA** [comment]
Maybe i'm missing something but i quick tested that instruction and got the same result.

```csharp
using System;
					
public class Program
{
	private uint PC = 0xBFC13644;
	
	  public struct Instr {
            public uint value;                     //raw
            public uint imm => value & 0xFFFF;     //Immediate value
            public uint imm_s => (uint)(short)imm; //Immediate value sign extended
        }
        private Instr instr;
	
	public static void Main() {
		Program program = new Program();
		program.init();
	}
	
	public void init() {
		instr.value = 0x1000fffc;
		
		uint regular = PC + (instr.imm_s << 2);
                uint casted = (uint)(PC + (short)(instr.imm_s << 2));
		
               Console.WriteLine($"{(instr.imm_s << 2):x8} {((short)(instr.imm_s << 2)):x8} {regular:x8} {casted:x8}");
               //Prints fffffff0 0000fff0 bfc13634 bfc13634
	}
}
```

¿Have you modified by any chance the Opcode Instr struct?

**Comment by fraser125** [comment]
Thank you very much for your patience with me. 
I did find the issue, it was my code and so very subtle. I'm not sure when it got changed but here is the difference. 

Your Code - Works
```csharp
            public uint imm => value & 0xFFFF;     //Immediate value
            public uint imm_s => (uint)(short)imm; //Immediate value sign extended
```
My Code - Doesn't work
```csharp
            public uint imm => value & 0xFFFF;     //Immediate value
            public uint imm_s => (uint)(short)value & 0xFFFF; //Immediate value sign extended
```
I needed to wrap the `value & 0xFFFF` in parens, or use `imm` like you did either way would of avoided my problem. 
I have a feeling I made the change when reviewing the code with a profiler.
Again, Thank you for your time.

**Pull request closed without merging**
