### PR TITLE
Split ProjectPSX in two projects :  Winforms one (ProjectPSX) and an Engine one (ProjectPSX.Engine)

### PR DESCRIPTION
**Pull request by ncmtl**
…Both namespaces are ProjectPSX. Broke Display in two (GPUDisplay and Display) to remove Winforms reference.

### CODE REVIEW

**Comment by ncmtl** [comment]
Hope I did it fast enough so that merge with your local branch stays simple.

**Comment by BluestormDNA** [comment]
Hello there!,

Sorry but I already handled the split, temporary i added a System.Drawing nugget on Core to not refactor anything from the GPU yet.

I wanted to make another Frontend (either GDI or OpenTK) to test if i could have several of them. Before pushing this.
But maybe I will try to push the winform one later and i will se how i handle the Drawing with the others in the future and return back to sound...

Do you happen to know anything about Xamarin btw?

**Comment by ncmtl** [comment]
That's great ! Actually I was not very comfortable on moving files between projects. As moves are tagged as delete + add, I was afraid that you could not merge easily. 

Don't know much about Xamarin (now MAUI), I mostly use Winforms or Blazor, sorry.

I'll wait for you commit to close the PR (or you can close it if you want).

**Comment by BluestormDNA** [comment]
Done: 840b25e05bccf5bc112edf459830309fa6cf79dd, 2cee141cde6c6d6ec78d25bb0b4df13e0c4bff71, 7060dc993b16997474bd6b4295eab78c895723c9,  hopefully I didn't break anything...

Took me a while because I wanted to get rid of the little drawing dependency on core. Ended up doing some refactor there. So now the core only haves a net core reference.
Also prepared the IHostWindow for Play for the coming CDDA and XA audio hopefully once i fix some cracks on XA decoding. There's still some work to do, like the main loop that it's in the core, but well that's work for other day I suppose...

I will be closing this. Thx for all. Your work on, https://github.com/BluestormDNA/ProjectPSX/pull/12 really helped me a lot.

If you wanna talk about emulation you can reach me at the Emudev Discord server at https://discord.com/invite/dkmJAes hopefully you can join, maybe we can talk about if it's possible to do something with blazor...

**Pull request closed without merging**
