### PR TITLE
Added a file picker for loading a "CD"

### PR DESCRIPTION
**Pull request by butler1233**
Swaps out the hardcoded file CD loading and replaces it with a file dialog where users can load any .bin file.

### CODE REVIEW

**Comment by Michanne** [comment]
@butler1233 you removed the comment that said it should ideally be through drag and drop onto the executable

**Comment by butler1233** [comment]
How's that? If will take a .Bin from a command line argument (order doesn't matter if more get added) and if one isn't supplied it will prompt for a file before the "CD" is loaded.

*edit* The command line argument will allow for drag and drop onto the exe, as well as loading through command line switches if you ever intend to use them too.

**Comment by BluestormDNA** [comment]
Hello!
Been very busy lately.
Thanks to @Michanne and @butler1233.

Never saw Environment.GetCommandLineArgs(); it's pretty amazing that you dont need to pass the string array here and there. Does it rely on something?

**Review by BluestormDNA — CHANGES_REQUESTED** [review]
I appreciate your PR, some things and sorry for the delay:

Can the Linq import be removed?
Can we still have a hardcoded default CD value and if null or something triggers the CD Dialog?
(That would be pretty handy as I do a lot of tests with a lot of re-runs and still having hardcoded CDs bypassing the dialog makes it easier to debug to me)
If you happen to have a better idea just tell me.
Can you format the code to be brackets on same line?

**Comment by lukasf** [comment]
@BluestormDNA An alternative approach for your default file names, now that command line arguments are supported: You can set command line arguments to use in VS debug sessions: Right-click the main C# project, Properties, Debug, now put the file name in "Command line arguments". Now whenever you start the project from VS, that file will automatically be opened.

**Comment by butler1233** [comment]
@BluestormDNA Here's the setting @lukasf was talking about:
image

Regarding the Linq import, it is required for the `.Any` and `First` calls. It makes it much more flexible with the ordering of the command line arguments if you do add more in future.

Regarding your request to "format the code to be brackets on the same line", that goes against the [C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#layout-conventions) set by Microsoft.

**Comment by BluestormDNA** [comment]
Nice thats enough for me.
Regarding the format i know im against the coding conventions. It's a personal preference.
Im gonna try to enforce this via .editorconfig.

**Pull request merged**
