### PR TITLE
Isolated Winforms from rest of solution

### PR DESCRIPTION
**Pull request by ncmtl**
Project should be splitable in two projects : a Winform project and a core/engine project. 

Got some fun reading on psx emulator thanks to this project. Thanks for sharing !

### CODE REVIEW

**Comment by BluestormDNA** [comment]
Hello there!

Thx for the PR,
Isolate the host is a very nice thing ive been delaying for so long so I really appreciate this. Very interested on splitting the project engine from the UI...

Also quick question: Can you remove the RX nugget dep?

**Comment by ncmtl** [comment]
Hi !

Thanks for taking the time to review my PR ! 

I can remove the dependency to Rx and replace Observables by plain events, but usually people move the opposite direction. Just a few short term benefits of using IObservable/Rx over events : 
- less memory leaks with Winforms (disposing subjets clear all references)
- easier management of event subcriptions (you can remove all references from event publisher or event subscriber)

Are you sure that's what you want? I'll just wait for your confirmation before doing it if you don't mind !

**Comment by BluestormDNA** [comment]
Maybe i'm missing something but haven't found a reference to RX on the code, only the nuget.
Also even thought this is personal,I'm not a big fan of Rx...
Anyway the nuget ads almost 4MB to a less than 300KB project.

**Comment by ncmtl** [comment]
No you are not missing anything. I initially used an IObservable and then removed it. I forgot to cleanup the Rx reference. It should be ok now. My bad, sorry about that !
Thanks for taking the time to answer back.

**Comment by ncmtl** [comment]
Also, not liking a library is a reason good enough for me !

**Comment by BluestormDNA** [comment]
Merged!

**Pull request merged**
