### PR TITLE
Set Window Text

### PR DESCRIPTION
**Pull request by Gaweph**
## Thread Safe Window Text change

https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls?redirectedfrom=MSDN

### CODE REVIEW

**Comment by BluestormDNA** [comment]
Thank you very much, I really appreciate your effort.
Before merging can you change the brace placement to match the style of the rest of the project?

**Comment by Michannne** [comment]
@BluestormDNA You may want to put that requirement in the CONTRIBUTING.md file, as typical C# formatting is brackets on newlines

**Comment by Gaweph** [comment]
@BluestormDNA . Done.

**Comment by BluestormDNA** [comment]
Format is not correct but it's my fault for not having guidelines and going against the C# standard on that thing...

Anyway i'm gonna merge this i'll format it when i touch that class again.

Thanks!

**Comment by willkuer** [comment]
You could enforce rules via .editorconfig most development tools respect it if existing.

Nice project btw

**Pull request merged**
